access_token_expiration: 300
refresh_token_expiration: 1209600
remember_clients: true
_core:
  default_config_hash: iIf5HmjnxW8tLdod1EQ19q4RQ5mkg-r5wBn2QFmitr8
public_key: /var/www/html/usha_sewing_dev/public.key
private_key: /var/www/html/usha_sewing_dev/private.key
